install:
	cp -fv awcc_autoboost.sh /usr/local/bin
	mkdir -pv /etc/awcc
	cp -fv awcc_autoboost.conf /etc/awcc/autoboost.conf
	mkdir -pv /etc/systemd/system
	cp -fv awcc_autoboost.service /etc/systemd/system/awcc_autoboost.service
